import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/fs.ts",
    "src/path.ts",
    "src/events.ts",
    "src/buffer.ts",
    "src/process.ts",
    "src/util.ts",
    "src/timers.ts",
    "src/os.ts",
    "src/stream.ts",
    "src/url.ts",
    "src/crypto.ts",
    "src/http.ts",
    "src/console.ts",
    "src/assert.ts",
    "src/child_process.ts",
    "src/module.ts",
    "src/rimraf.ts",
    "src/esbuild.ts",
    "src/dns.ts",
    "src/readline.ts",
    "src/string_decoder.ts",
    "src/tty.ts",
    "src/zlib.ts",
    "src/types.ts",
  ],
  format: ["esm", "cjs"],
  dts: true,
  clean: true,
  sourcemap: true,
  external: ["@lifo-sh/kernel"],
});
